# Generated by Django 3.1.4 on 2020-12-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttkom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='post-photo'),
        ),
    ]
