# Generated by Django 3.1.4 on 2020-12-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttkom', '0002_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pp',
            field=models.ImageField(null=True, upload_to='user-photo'),
        ),
    ]
