# Generated by Django 3.1.4 on 2021-01-05 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ttkom", "0003_profile_pp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="blog_comment", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
