# Generated by Django 3.1.4 on 2021-01-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="subheading",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projet",
            name="skills",
            field=models.ManyToManyField(blank=True, to="portfolio.Skill"),
        ),
    ]
