# Generated by Django 3.1.4 on 2021-03-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='Index_wording',
        ),
    ]
