# Generated by Django 3.1.4 on 2021-03-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210325_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fk_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.projet', verbose_name='projet categoriser')),
            ],
        ),
    ]
