# Generated by Django 3.1.4 on 2021-03-25 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='fk_projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='fk_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.category', verbose_name='projet categoriser'),
            preserve_default=False,
        ),
    ]
